### ISSUE TITLE
Sora yori mo Tooi Basho Episode 7 subtitles not properly working in VLC Media Player

### ISSUE THREAD

**Issue by Satoshiii-DCS** [nedragrevev/custom-subs#1]
The subtitles start out just fine before it starts experiencing trouble displaying in the OP then completely stops showing by the first scene after the OP.

![vlcsnap-2020-07-01-17h29m06s921](https://user-images.githubusercontent.com/61380847/86228145-9b30c100-bbc0-11ea-9aa0-a7da6f933ff4.png)

![vlcsnap-2020-07-01-17h29m43s655](https://user-images.githubusercontent.com/61380847/86228168-a4219280-bbc0-11ea-9851-659109f5d54c.png)

**Comment by nedragrevev** [comment]
Bug confirmed on VLC.
My initial suspicions were correct: VLC doesn't like the vector drawings for the episode title (which were very, very long lines of code).

Removed vector drawings and replaced with suitable chalk font. This version works for me on VLC now. See if works for you.

And also, I've also finally got around to replacing the Vollkorn font, which libass incorrectly renders (libass is the subtitle renderer that VLC and many other players use). It affected episodes 1-5, 7 & 8.

**Comment by Satoshiii-DCS** [comment]
Subtitles are now working perfectly. Thanks for the improvement!

![vlcsnap-2020-07-02-21h47m39s518](https://user-images.githubusercontent.com/61380847/86366811-d4932a80-bcad-11ea-9506-bf8794aca53a.png)
![vlcsnap-2020-07-02-21h47m32s246](https://user-images.githubusercontent.com/61380847/86366825-d9f07500-bcad-11ea-8f69-6636d474c3d3.png)
