### ISSUE TITLE
Question about multiple .ass files

### ISSUE THREAD

**Issue by jordantsao** [nedragrevev/custom-subs#10]
I'm using your subs for Violet Evergarden. I'm a bit confused as to why there are separate .ass files for the main subs and for "signs and songs." As far as I understand, I can only mux them independently as separate tracks anyway so there's no way to play them simultaneously. Is there a way to combine the files into one track somehow or am I understanding wrong?

Thanks for making these by the way.

**Comment by FreeTheTech101** [comment]
The "Signs and Songs" tracks only contain, well, the signs and songs. The other set of subtitles contain dialogue, signs, and songs. Generally, you'd use the signs and songs track if you are watching dubbed, as they cover any aspects that are still in Japanese.

**Comment by nedragrevev** [comment]
FreeTheTech101 is correct. The signs and songs tracks are independent of the main, unlabelled tracks and only needed if you want to watch the English dub.

Just to make it a bit clearer: "signs" means any onscreen text in Japanese. In VE it's practically non-existent except for a couple of location cards/titles here and there.

Re the songs in VE, IIRC there was at least one song in the English dub not present in the original Japanese dub which I've included in the "signs and songs" track (romaji and translated lyrics).
