### ISSUE TITLE
ARIA The ANIMATION Wrong Files

### ISSUE THREAD

**Issue by ehoneyse** [nedragrevev/custom-subs#2]
Hey, happy to find these subtitles, they look great! 

Unless I am going crazy, the ARIA The ANIMATION zip file contains the files for ARIA The ORIGINATION (at least for the most recent commit).

**Comment by nedragrevev** [comment]
Not sure what I was doing. I have reviewed the whole series recently and must've mistakenly packaged up the wrong season.

Just updated so should hopefully all good now.
I'm glad someone is making use of these ARIA subs. Thanks!

08d0f396294928e54112aeea7aedf6d66a553cc1
