### ISSUE TITLE
I want to eat your pancreas - US BD - Timing

### ISSUE THREAD

**Issue by FreeTheTech101** [nedragrevev/custom-subs#7]
After working with the US BD for a few days, I was able to determine that a 1000MS delay to all included subtitles (for both the main movie and the extras) syncs perfectly. Would it be possible to get a note included with the included TXT for future reference? I am sure there would be some people out there who would prefer your amazing work over the included PGS subtitles.

**Comment by nedragrevev** [comment]
Thanks for the info and feedback. This is really appreciated!
I thought about adding only a note, but it's easy enough to just add versions with the timings adjusted, so I've done that. Would you be able to check if those versions sync up perfectly?

**Comment by FreeTheTech101** [comment]
Did a quick runthrough with the "Signs and Songs" and "Honorifics" subtitles, and all looks good from here! Timing and tracking is spot on. Once again, thank you so much for your work 🙂

Main Movie - Signs and Songs:
![vlcsnap-2022-07-16-08h27m51s820](https://user-images.githubusercontent.com/7614507/179354980-95921092-d914-4d2d-a9e8-48a5a28835af.png)
![vlcsnap-2022-07-16-08h28m40s325](https://user-images.githubusercontent.com/7614507/179354986-50076259-17d6-4f9c-9dbe-b9ac58c1bf9e.png)
![vlcsnap-2022-07-16-08h28m58s138](https://user-images.githubusercontent.com/7614507/179354987-8c8618b3-03a5-45ef-8830-1d52fea05ef8.png)

Main Movie - Honorifics:
![vlcsnap-2022-07-16-08h30m26s708](https://user-images.githubusercontent.com/7614507/179354989-a2f01a1f-483c-4434-9399-4f411928fab4.png)
![vlcsnap-2022-07-16-08h32m28s327](https://user-images.githubusercontent.com/7614507/179355007-834da80e-ad55-493c-954c-1e6ab7446500.png)
![vlcsnap-2022-07-16-08h33m03s149](https://user-images.githubusercontent.com/7614507/179355023-7a374d6f-3a29-40e4-9272-ed958ec15945.png)

"Fanfare":
![vlcsnap-2022-07-16-08h42m15s369](https://user-images.githubusercontent.com/7614507/179355391-629c4eca-bdf3-47a2-ba6e-62a5987939a1.png)

**Comment by nedragrevev** [comment]
Great. Glad it worked without issue.
Thanks for all your help.
