### ISSUE TITLE
Chihayafuru 2 Ep 3 subs disappeared.

### ISSUE THREAD

**Issue by mibby** [nedragrevev/custom-subs#9]
Present here.
https://github.com/nedragrevev/custom-subs/commit/328725e9bcc5a86e132f76df54d9632987e01ecb

Disappeared in latest commit.
https://github.com/nedragrevev/custom-subs/commit/0f3091092387ba211c6d22b93eff01532306bc6f

**Comment by nedragrevev** [comment]
Not sure what was I doing, but I just readded it (zero changes, just a new archive to include the dialogue subs for EP03).
Thanks for the report.
